# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/aque_db
spring.datasource.username=${DB_USER:aque}
spring.datasource.password=${DB_PASS:aque}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.show-sql=true
# Logging
logging.level.com.aque=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.flywaydb=INFO